deniszholob/factorio-cheat-sheet

- src/app/app.module.ts
- src/app/views/cheat-sheets/index.ts
- src/app/views/cheat-sheets/productivity-module-payoffs/productivity-module-payoffs.component.html
- src/app/views/cheat-sheets/productivity-module-payoffs/productivity-module-payoffs.component.ts
- src/app/views/main/main.component.html
- src/assets/data/productivity-module-payoffs.json
- src/global-styles/_table.scss
Add Productivity Module Payoffs Sheet
> Add Productivity Module Payoffs Sheet

- src/app/app.module.ts
- src/app/services/data.service.ts
- src/app/views/cheat-sheets/common-ratios/common-ratios.component.html
- src/app/views/cheat-sheets/common-ratios/common-ratios.component.ts
- src/app/views/cheat-sheets/index.ts
- src/app/views/main/main.component.html
- src/assets/data/common-ratios.json
- src/global-styles/_table.scss
- src/global-styles/styles.scss
> Add Common Ratios Sheet

- src/app/app.component.html
- src/app/app.module.ts
- src/app/shared/app-settings.ts
- src/app/views/credits/credits.component.html
- src/app/views/index.ts
- src/app/views/intro/intro.component.html
- src/app/views/main/main.component.html
- src/app/views/overview/overview.component.html
- src/app/views/overview/overview.component.ts
- src/global-styles/_intro.scss
Add Overview section, add titles to sections
> Add Overview section, add titles to sections

- src/app/app.module.ts
- src/app/services/data.service.ts
- src/app/shared/factorio-icon/factorio-icon.component.scss
- src/app/views/cheat-sheets/index.ts
- src/app/views/cheat-sheets/science/science.component.html
- src/app/views/cheat-sheets/science/science.component.scss
- src/app/views/cheat-sheets/science/science.component.ts
- src/app/views/main/main.component.html
- src/assets/data/science.json
- src/global-styles/_input-group.scss
- src/global-styles/styles.scss
Add Science Sheet and Input group styling
> Add Science Sheet and Input group styling

- src/app/app.module.ts
- src/app/services/data.service.ts
- src/app/shared/factorio-icon/factorio-icon.component.scss
- src/app/views/cheat-sheets/belt-throughput/belt-throughput.component.html
- src/app/views/cheat-sheets/common-ratios/common-ratios.component.html
- src/app/views/cheat-sheets/common-ratios/common-ratios.component.ts
- src/app/views/cheat-sheets/index.ts
- src/app/views/cheat-sheets/material-processing/material-processing.component.html
- src/app/views/cheat-sheets/material-processing/material-processing.component.scss
- src/app/views/cheat-sheets/material-processing/material-processing.component.ts
- src/app/views/cheat-sheets/productivity-module-payoffs/productivity-module-payoffs.component.html
- src/app/views/cheat-sheets/productivity-module-payoffs/productivity-module-payoffs.component.ts
- src/app/views/cheat-sheets/science/science.component.html
- src/app/views/cheat-sheets/science/science.component.ts
- src/app/views/main/main.component.html
- src/app/views/nav/nav.component.ts
- src/assets/data/material-processing.json
- src/assets/data/nav.json
- src/global-styles/_table.scss
- src/global-styles/_variables.scss
Add Material Processing Sheet, Nav data from json.
> Add Material Processing Sheet, Nav data from json.

- src/app/app.module.ts
- src/app/views/cheat-sheets/belt-throughput/belt-throughput.component.html
- src/app/views/cheat-sheets/index.ts
- src/app/views/cheat-sheets/links/links.component.html
- src/app/views/cheat-sheets/links/links.component.ts
- src/app/views/cheat-sheets/material-processing/material-processing.component.html
- src/app/views/main/main.component.html
- src/assets/data/links.json
- src/assets/data/nav.json
- src/global-styles/_table.scss
- src/global-styles/styles.scss
> Add Link Sheet, minor fixes

- src/app/app.module.ts
- src/app/views/cheat-sheets/belt-throughput/belt-throughput.component.html
- src/app/views/cheat-sheets/index.ts
- src/app/views/cheat-sheets/mining/mining.component.html
- src/app/views/cheat-sheets/mining/mining.component.scss
- src/app/views/cheat-sheets/mining/mining.component.ts
- src/app/views/cheat-sheets/tips/tips.component.html
- src/app/views/main/main.component.html
- src/assets/data/material-processing.json
- src/assets/data/mining.json
- src/assets/data/nav.json
- src/index.html
Add Mining Sheet, Fixes, Analytics
> Add Mining Sheet, Fixes, Analytics

- src/app/app.module.ts
- src/app/shared/factorio-icon/factorio-icon.component.scss
- src/app/views/cheat-sheets/basic-power/basic-power.component.html
- src/app/views/cheat-sheets/basic-power/basic-power.component.ts
- src/app/views/cheat-sheets/belt-throughput/belt-throughput.component.html
- src/app/views/cheat-sheets/index.ts
- src/app/views/cheat-sheets/material-processing/material-processing.component.html
- src/app/views/cheat-sheets/mining/mining.component.html
- src/app/views/cheat-sheets/mining/mining.component.scss
- src/app/views/cheat-sheets/science/science.component.html
- src/app/views/cheat-sheets/tips/tips.component.html
- src/app/views/main/main.component.html
- src/assets/data/basic-power.json
- src/assets/data/material-processing.json
- src/assets/data/nav.json
- src/global-styles/styles.scss
Add Power Sheet, Material Processing + Mining + Other Minor Fixes
> Add Power Sheet, Material Processing + Mining + Other Minor Fixes

- src/app/app.module.ts
- src/app/shared/app-settings.ts
- src/app/views/cheat-sheets/basic-power/basic-power.component.html
- src/app/views/cheat-sheets/belt-throughput/belt-throughput.component.html
- src/app/views/cheat-sheets/common-ratios/common-ratios.component.html
- src/app/views/cheat-sheets/index.ts
- src/app/views/cheat-sheets/material-processing/material-processing.component.html
- src/app/views/cheat-sheets/nuclear-power/nuclear-power.component.html
- src/app/views/cheat-sheets/nuclear-power/nuclear-power.component.ts
- src/app/views/cheat-sheets/oil-refining/oil-refining.component.html
- src/app/views/cheat-sheets/oil-refining/oil-refining.component.ts
- src/app/views/cheat-sheets/tips/tips.component.html
- src/app/views/main/main.component.html
- src/assets/data/common-ratios.json
- src/assets/data/nav.json
- src/assets/data/nuclear-power.json
- src/assets/data/oil-refining.json
Common ratios improvement with rocket components
Nucke Power, add steam tank calculations
Table center formatting
Minor Text changes
> Add Oil Sheet and fixes

- src/app/views/cheat-sheets/material-processing/material-processing.component.html
Remove an errant asterisk and moved the note reference asterisks to a more appropriate location.
> Fixed asterisks in material processing

- src/app/views/cheat-sheets/fluid-wagon-transfer/fluid-wagon-transfer.component.html
Also reword the notice about pumps and tanks.
> Say that fluid wagons can carry different fluids in different tanks

- src/app/views/cheat-sheets/modules-and-beacons/modules-and-beacons.component.html
- src/app/views/cheat-sheets/nuclear-power/nuclear-power.component.html
- src/app/views/cheat-sheets/productivity-module-payoffs/productivity-module-payoffs.component.html
- src/app/views/cheat-sheets/science/science.component.html
- src/assets/data/links.json
* Add Guides in the links
* Prod Modules and Labs/Research
* Add SRE tables to Nuclear Section
* Add Research Unlocks Table for Science
> Another Improvement round

- src/app/views/cheat-sheets/tips/tips.component.html
> Corrected minor typo in tips section

- src/app/views/cheat-sheets/inserter-throughput/inserter-throughput.component.html
- src/app/views/cheat-sheets/nuclear-power/nuclear-power.component.ts
- src/assets/data/inserter-throughput.json
* Update Inserter Data; was inconsistent for higher stacks/inserter types
* Fix lint spacing issue
> Update Inserter Table #73

- package.json
- src/app/services/clipboard.service.ts
- src/app/services/index.ts
- src/app/views/cheat-sheets/balancers/balancers.component.html
- src/app/views/cheat-sheets/balancers/balancers.component.ts
- src/app/views/cheat-sheets/inserter-capacity-bonus/inserter-capacity-bonus.component.html
- src/assets/data/balancers.json
- src/global-styles/_button.scss
* Fix Balancer Wiki Link (#88)
* Make a list in 1st paragraph
* Add a copy button for blueprints in table
* Add Balancer Guide links
> Balancer Sheet Work (#84 #88)

- src/app/views/cheat-sheets/material-processing/material-processing.component.html
- src/app/views/cheat-sheets/mining/mining.component.html
- src/assets/data/material-processing.json
- src/assets/data/mining.json
Update values for materials processing and mining.
should fix issues:
Update Material Processing for 0.17: https://github.com/deniszholob/factorio-cheat-sheet/issues/97
Update Mining for 0.17: https://github.com/deniszholob/factorio-cheat-sheet/issues/79
I also removed the text that mentioned 0.17 that I had previously added.
> V017 updates, lets try this again, correctly

- src/app/views/cheat-sheets/oil-refining/oil-refining.component.html
- src/assets/data/oil-refining.json
- Changed Coal Liquefaction ratios.
- For Accurate Liquefaction + cracking: removed plastic bar production.
- Changed links from Reddit to wiki.
> Coal Liquefaction

- src/app/views/cheat-sheets/oil-refining/oil-refining.component.html
- src/app/views/cheat-sheets/science/science.component.html
- src/app/views/cheat-sheets/train-speed/train-speed.component.html
- src/assets/data/basic-power.json
- src/assets/data/common-ratios.json
- src/assets/data/productivity-module-payoffs.json
- src/assets/data/science.json
- src/assets/data/train-colors.json
RE: Issue #120 
I've updated the data assets with the new IDs, we well as HTML components.
> Update icon IDs to match Factorio wiki

- src/app/views/overview/overview.component.html
- Spelling/grammar fixes.
- Added a dot on the line end at "Known issues", a dot is used at the end of every bullet point line, but not here. 
- Changed name of .pdf file to 0.17 (this will probably give a file not found error?)
> Spelling/grammar fixes, pdf filename for 0.17

- src/app/views/cheat-sheets/basic-power/basic-power.component.html
- src/app/views/cheat-sheets/train-speed/train-speed.component.html
- src/assets/data/basic-power.json
- src/assets/data/train-speed.json
* Update fuel in Basic Power Sheet
* Update fuel bonuses in Train Speed Sheet
* Rename Train Speed Sheet to Vehicle Fuel Bonus
> #78 Update fuel for 0.17

- src/app/views/cheat-sheets/common-ratios/common-ratios.component.html
- src/app/views/cheat-sheets/material-processing/material-processing.component.html
- src/app/views/cheat-sheets/nuclear-power/nuclear-power.component.html
- src/app/views/cheat-sheets/science/science.component.html
- src/app/views/cheat-sheets/science/science.component.ts
- src/assets/data/common-ratios.json
- src/assets/data/science.json
- src/global-styles/styles.scss
* #93 Update Common Ratios
* #93 Add more basic ratios
* #90 Remove science Unlocks
* #90 Swap Military and Chem science positions
* Misc adjustments
> #93 Update Common Ratios

- src/app/views/cheat-sheets/common-ratios/common-ratios.component.html
- src/app/views/cheat-sheets/oil-refining/oil-refining.component.html
- src/assets/data/common-ratios.json
- src/assets/data/oil-refining.json
* #119 Update Oil cracking Ratios
* #119 Update Coal Liquefaction ratios
* #93 Add machine speeds onto common-ratios
> #119 Update Oil Data

- CONTRIBUTING.md
- README.md
- src/app/views/overview/overview.component.html
Reverts deniszholob/factorio-cheat-sheet#127
> Revert "Add temp 0.17 info"

- src/assets/data/material-processing.json
merging branches is fun. fixes the same stuff as in the now abandoned v017 branch.
https://github.com/deniszholob/factoio-cheat-sheet/issues/140
> Fix uranium processing numbers, merge to master

- src/app/views/cheat-sheets/science/science.component.html
- src/app/views/cheat-sheets/train-speed/train-speed.component.html
- src/assets/data/basic-power.json
- src/assets/data/common-ratios.json
- src/assets/data/productivity-module-payoffs.json
- src/assets/data/science.json
- src/assets/data/train-colors.json
> Fixed the icons of the 0.16 cheatsheet

- src/app/views/cheat-sheets/balancers/balancers.component.html
- src/app/views/cheat-sheets/basic-power/basic-power.component.html
- src/app/views/cheat-sheets/common-ratios/common-ratios.component.html
- src/app/views/cheat-sheets/fluid-wagon-transfer/fluid-wagon-transfer.component.html
- src/app/views/cheat-sheets/mining/mining.component.html
- src/app/views/cheat-sheets/modules-and-beacons/modules-and-beacons.component.html
- src/app/views/cheat-sheets/nuclear-power/nuclear-power.component.html
- src/app/views/cheat-sheets/oil-refining/oil-refining.component.html
- src/app/views/cheat-sheets/tips/tips.component.html
- src/app/views/cheat-sheets/train-colors/train-colors.component.html
Modded all hrefs to open in a new tab.
> target="_blank"

- src/app/shared/cheat-sheet/cheat-sheet.component.html
- src/app/views/cheat-sheets/modules-and-beacons/modules-and-beacons.component.html
- src/global-styles/_card.scss
> Added Toggle Collapse to Card Headers

- src/assets/data/inserter-throughput.json
> Updated Stack Inserter Throughput to match wiki

- src/app/views/cheat-sheets/science/science.component.html
- src/app/views/cheat-sheets/science/science.component.scss
- src/app/views/cheat-sheets/science/science.component.ts
Adds a labs required calculator
Useful for megabasing
> Labs Required

- src/app/views/cheat-sheets/balancers/balancers.component.html
> Fix spelling

- src/app/views/cheat-sheets/basic-power/basic-power.component.html
- src/app/views/cheat-sheets/tips/tips.component.html
- src/assets/data/links.json
Hi @deniszholob,
I've taken my changes that I linked to #180, and merged the lot, and rebased on your master branch. This should be okay now.
Note that this pull-request **does not contain** the changes from #184. Do you want that to be included too?
I hope this is what you wanted. :) If not let me know and I'll do some more rebasing... :smile: 
HonkingGoose
> One pr for issue 180

- src/app/shared/app-settings.ts
- src/app/views/cheat-sheets/oil-refining/oil-refining.component.html
- src/app/views/overview/overview.component.html
- src/assets/data/common-ratios.json
- src/assets/data/oil-refining.json
- src/global-styles/_table.scss
* #190 Basic oil ratio changes
* #194 Advanced oil and cracking ratio change
* #192 Chemical Science changed
> #190 Oil Recipe Change

- CNAME
- angular.json
- src/app/shared/app-settings.ts
- src/app/views/cheat-sheets/cargo-wagon-transfer/cargo-wagon-transfer.component.html
- src/app/views/cheat-sheets/cargo-wagon-transfer/cargo-wagon-transfer.component.ts
- src/app/views/cheat-sheets/material-processing/material-processing.component.html
- src/app/views/cheat-sheets/oil-refining/oil-refining.component.html
- src/assets/data/cargo-wagon-transfer.json
- src/assets/data/oil-refining.json
- src/assets/data/train-colors.json
Tweaks and GH Issue Fixes
* #215 Add CNAME to have gh-pages auto publish to domain
* #212, #181 update transfer table to use inserter data instead
* #204 Remove 0.16 CS link
* #203 Update Train colors
* #180 Add "on avg" to uranium processing note (+2 squashed commit)
* Add Cargo Wagon items/chest table
* Update Version
* Spelling fixes
> Tweaks and GH Issue Fixes

- CNAME
- angular.json
- src/app/views/cheat-sheets/cargo-wagon-transfer/cargo-wagon-transfer.component.ts
- src/app/views/cheat-sheets/productivity-module-payoffs/productivity-module-payoffs.component.ts
* Remove duplicate CNAME file, fic path in angular.json
* Lint fixes
> Build Issue Fix

- .vscode/settings.json
- src/app/app.module.ts
- src/app/definitions/BeltThroughput.d.ts
- src/app/definitions/MiningRate.d.ts
- src/app/pipes/ceiling.pipe.ts
- src/app/pipes/index.ts
- src/app/pipes/time.pipe.ts
- src/app/views/cheat-sheets/common-ratios/common-ratios.component.html
- src/app/views/cheat-sheets/inserter-throughput/inserter-throughput.component.html
- src/app/views/cheat-sheets/inserter-throughput/inserter-throughput.component.scss
- src/app/views/cheat-sheets/inserter-throughput/inserter-throughput.component.ts
- src/app/views/cheat-sheets/mining/mining.component.html
- src/app/views/cheat-sheets/mining/mining.component.scss
- src/app/views/cheat-sheets/mining/mining.component.ts
- src/app/views/cheat-sheets/nuclear-power/nuclear-power.component.ts
- src/app/views/cheat-sheets/train-colors/train-colors.component.html
- src/assets/data/mining.json
- src/global-styles/_input-group.scss
- src/global-styles/_table.scss
- src/global-styles/print.scss
* Rework the mining section to auto calculate the table along with productivity
* Update styling for print
* Update data and add model definitions
* Add ceiling pipe
* Fix caption, input-group styling
> #10 Mining Section Productivity

- src/app/views/cheat-sheets/tips/tips.component.html
- Replace "this is also can be toggled in" with "you can also use the"
- Add tip on which button to use on the shortcut bar to toggle the ALT mode
> Improve section on ALT mode use via shortcut bar

- src/app/shared/app-settings.ts
- src/assets/data/belt-throughput.json
* Closes #224 - Update Factorio versions
* Closes #225 - Update belt data tiers to fix mining table presentation
> Quick Updates

- README.md
- src/global-styles/_button.scss
- src/global-styles/_scroll-bar.scss
* Get rid of the blue colors for click and focus
* Decrease scroll bat radius
* Update readme build status link
> Fix button styling

- src/app/app.component.html
- src/app/views/nav/nav.component.html
- src/app/views/nav/nav.component.ts
- src/global-styles/_side-nav.scss
- src/global-styles/styles.scss
Closes #202 change nav behavior #228
* Nav now stays open on the right on large screens > 1366px
* Nav buttons stay sticky
> Closes #202 change nav behavior

- src/app/views/cheat-sheets/balancers/balancers.component.html
- src/app/views/cheat-sheets/balancers/balancers.component.ts
- src/assets/data/balancers.json
Closes #232 - Update Balancer Page
* Replace balancer table with tips
* Add 4x4 and 8x8 balancer links
* Reorder Balancer footer link section
> Closes #232 - Update Balancer Page

- src/app/views/cheat-sheets/common-ratios/common-ratios.component.html
- src/app/views/cheat-sheets/links/links.component.html
- src/app/views/cheat-sheets/tips/tips.component.html
- src/assets/data/common-ratios.json
- src/assets/data/links.json
- src/global-styles/styles.scss
* Reorganize links
* Add creator blueprint links
* Add Space science ratio to table
* Rich Text wiki link
> Update the Links section

- src/app/app.module.ts
- src/app/definitions/TrainColors.d.ts
- src/app/pipes/index.ts
- src/app/pipes/replace.pipe.ts
- src/app/views/cheat-sheets/train-colors/train-colors.component.html
- src/app/views/cheat-sheets/train-colors/train-colors.component.ts
- src/assets/data/train-colors.json
- src/global-styles/_switch.scss
- src/global-styles/styles.scss
* Add generated color data from reddit
* Add a switch to toggle b/w tailored and generated colors
> Update Train Colors

- src/app/views/cheat-sheets/basic-power/basic-power.component.html
- src/app/views/cheat-sheets/basic-power/basic-power.component.ts
- src/assets/data/basic-power.json
* #242 Add Usable to Total solar power ratio
* #187 Flip row/cols for coal table to make it more copmact
> Closes #242 Add Solar Power Ratio

- .vscode/settings.json
- src/app/shared/app-settings.ts
- src/app/views/cheat-sheets/modules-and-beacons/modules-and-beacons.component.html
- src/assets/data/links.json
Update code/bugfix
* Closes #255 Update step for input fields in module calculator
* // => https:// url in app-settings
* Update Factorio version to latest
* Add JdPlays new tutorial guide
> Some code updates/bugfix

- src/assets/data/fluid-wagon-transfer.json
> Update fluid transfer times

- src/app/views/cheat-sheets/material-processing/material-processing.component.html
Changes this PR makes:
- Improve grammar in multiple sentences.
- Add missing punctuation.
- Expand abbreviation into the full word.
> Small fixes material processing section

- src/app/views/cheat-sheets/basic-power/basic-power.component.html
- src/app/views/cheat-sheets/cargo-wagon-transfer/cargo-wagon-transfer.component.html
- src/app/views/cheat-sheets/fluid-wagon-transfer/fluid-wagon-transfer.component.html
- src/app/views/cheat-sheets/inserter-capacity-bonus/inserter-capacity-bonus.component.html
- src/app/views/cheat-sheets/inserter-throughput/inserter-throughput.component.html
- src/app/views/cheat-sheets/modules-and-beacons/modules-and-beacons.component.html
- src/app/views/cheat-sheets/nuclear-power/nuclear-power.component.html
- src/app/views/cheat-sheets/oil-refining/oil-refining.component.html
- src/app/views/cheat-sheets/science/science.component.html
- src/app/views/cheat-sheets/tips/tips.component.html
- src/app/views/cheat-sheets/train-colors/train-colors.component.html
- src/app/views/cheat-sheets/vehicle-fuel-bonus/vehicle-fuel-bonus.component.html
Here you go! The rest of the small fixes into one pull request. 🚀 
In general the changes are:
- Rewrites of some sentences for clarity
- Expand abbreviations like b/w, esp
- Add unit of measurements
- Add degrees symbol before the Celsius unit
- Fix some white-space errors
- Add punctuation where necessary
- Fix some small style annoyances (text was just too small to read comfortably)
- Fix capitalization
- Fix grammar
I've contained each change with a commit, so we can chuck out what you don't want easily. 😄 
If you want to merge the work but don't want to end with 40+ commits on the `master` branch after the merge: click on the arrow that's just next to the merge button, and select the "Squash and merge" option. That will squash all commits into a single commit. This way you'll have …
> All other small fixes

- src/app/views/cheat-sheets/balancers/balancers.component.html
Changes this PR makes:
- Improve grammar.
- Simplify sentences.
- Improve inherent belt balancing explanation.
- Move a sentence into the relevant section.
- Add punctuation at the end of sentences.
> Small fixes balancers section

- src/app/views/cheat-sheets/links/links.component.html
- src/app/views/overview/overview.component.html
- src/assets/data/links.json
Add some more links to the links section - mostly communities
> Add more links

- src/app/views/cheat-sheets/belt-throughput/belt-throughput.component.html
- src/app/views/cheat-sheets/tips/tips.component.html
- src/assets/data/links.json
Closes #290 Update Links
* Update MojoD link, and add Factorio server link
* Minor wording changes
> Closes #290 Update Links

- src/app/views/cheat-sheets/inserter-capacity-bonus/inserter-capacity-bonus.component.html
- src/assets/data/inserter-throughput.json
- src/assets/data/links.json
* Fix inserter link
* Remove factorio school link (dne anymore)
> #294 Fix Broken image link

- src/app/views/cheat-sheets/balancers/balancers.component.html
Balancer book link moved, see https://www.reddit.com/r/factorio/comments/jqfhlu/balancers_illustrated_1_through_8_balancers/gbmnml2/?utm_source=reddit&utm_medium=web2x&context=3
> Update Balancer Book link

- src/assets/data/links.json
> #304 Add another website for blueprints

- src/app/views/cheat-sheets/science/science.component.html
Closes #276
* Add tip on space fish
* Add wiki links
* Rephrase formula wording (consumption -> production), see #302
> #276 Space Fish and Research

- src/app/views/cheat-sheets/links/links.data.ts
See https://github.com/demodude4u/Factorio-FBSR/issues/142#issuecomment-1115197945
> Fixed blueprintbot invite link

- src/app/app.component.html
- src/app/shared/cheat-sheet/cheat-sheet.component.html
- src/index.html
- src/styles/styles.scss
Testing out google adsese, hopefully this isnt very intrusive as i hate ads myself that are in your face/those that interrupt your flow.
So what im trying is:
Placing a text ad at end of every sheet "card" (this maybe too much, but i cannot see the result in my local env... -_-)
Placing a picture ad at the top of the annex section (this is at the very end so should be bad at all)
Also i used the customized theme on the ads to match the theme of this app as close as i could
> Try google adsense

- src/app/views/cheat-sheets/mining/mining.component.html
- src/app/views/cheat-sheets/mining/mining.component.ts
> Fix a regression error in the calculation

- src/app/shared/icon-ratio-composite/icon-ratio-composite.component.html
- src/app/shared/icon-ratio-composite/icon-ratio-composite.component.stories.ts
- src/app/shared/icon-ratio-composite/icon-ratio-composite.component.ts
- src/app/shared/ratio/ratio.component.html
- src/app/shared/ratio/ratio.component.stories.ts
- src/app/shared/ratio/ratio.component.ts
- src/app/views/cheat-sheets/cs-common-ratios/common-ratios.data.ts
- src/app/views/cheat-sheets/cs-common-ratios/cs-common-ratios.component.html
- src/app/views/cheat-sheets/cs-common-ratios/cs-common-ratios.component.stories.ts
- src/app/views/cheat-sheets/cs-common-ratios/cs-common-ratios.component.ts
- src/app/views/cheat-sheets/cs-common-ratios/machine-speeds.data.ts
- src/app/views/cheat-sheets/cs-common-ratios/rocket-ratios.data.ts
- src/styles/_icon-composite.scss
Added rates back into the ratios
Added note about rounding
Reordered some rocket ratios
Closes #289 - Added steel to rail ratio
> #283 Ratio tweaks

- src/app/app.component.html
- src/app/views/cheat-sheets/cs-common-ratios/common-ratios.data.ts
- src/app/views/cheat-sheets/cs-common-ratios/cs-common-ratios.component.html
- src/app/views/nav/nav.component.html
- src/app/views/overview/overview.component.html
- src/styles/print.scss
* Closes #298 Fix light pdf text contrast on icons
* Closes #362 Link to github releases for pdf and old cheat sheets, remove annex section and link
* Update RC ratio for plastic to be more accurate
> PDF fixes and hosting

- src/app/app.component.ts
- src/app/app.module.ts
- src/app/shared/cheat-sheet-template/cheat-sheet-template.component.html
- src/ngsw-config.json
* Add on destroy unsub
* Add service worker wiki image urls
* Enable native angular anchor scrolling
* Disable ngbcollapse animation
> #361 Try to increase performance

- .github/workflows/branch.yml
- angular.json
- build/build.sh
- package.json
- src/app/cheat-sheets/game-base/combat/combat.component.ts
- src/app/cheat-sheets/game-base/modules-and-beacons/modules-and-beacons.component.ts
- src/app/cheat-sheets/game-base/nuclear-power/sre-matrix/matrix-generator.ts
- src/app/cheat-sheets/game-base/tips/tips.component.ts
- src/app/services/data.service.ts
- src/app/shared/icon-ratio-composite/icon-ratio-composite.component.ts
- src/styles/_input-group.scss
* Per angular docs, copy index to 404 page using the build script
* Remove linting from build, add as a separate command
* Add text wrapping to select field
> Support deep linking to github pages like  /something #235

- src/app/cheat-sheets/game-base/mining/mining.component.scss
- src/app/cheat-sheets/game-base/nuclear-power/nuclear-power.component.html
- src/app/cheat-sheets/game-base/nuclear-power/nuclear-power.component.ts
- src/styles/_input-group.scss
* Add miner and chem plant icons
* Add calculator source
* Fix flex-overflow on input groups for mobile
* Closes #377
> #377 Add miners to Reactor-Centrifuge ratio

- src/app/cheat-sheets/game-base/tips/tips.component.html
> Remove outdated debug options

- src/app/cheat-sheets/game-base/balancers/balancers.component.html
- src/app/cheat-sheets/game-base/basic-power/basic-power.component.html
- src/app/cheat-sheets/game-base/belts/belts.component.html
- src/app/cheat-sheets/game-base/cargo-wagon-transfer/cargo-wagon-transfer.component.html
- src/app/cheat-sheets/game-base/combat/combat.component.html
- src/app/cheat-sheets/game-base/cs-common-ratios/cs-common-ratios.component.html
- src/app/cheat-sheets/game-base/fluid-wagon-transfer/fluid-wagon-transfer.component.ts
- src/app/cheat-sheets/game-base/fluid-wagon-transfer/fluid-wagon-transfer.data.ts
- src/app/cheat-sheets/game-base/links/links.data.ts
- src/app/cheat-sheets/game-base/mining/mining.component.html
- src/app/cheat-sheets/game-base/modules-and-beacons/modules-and-beacons.component.html
- src/app/cheat-sheets/game-base/nuclear-power/nuclear-power.component.html
- src/app/cheat-sheets/game-base/nuclear-power/nuclear-power.component.ts
- src/app/cheat-sheets/game-base/tips/tips.component.html
- src/app/layout/footer/footer.component.html
- src/app/layout/nav/nav.component.ts
- src/app/layout/overview/overview.component.html
- src/app/shared/factorio-icon/factorio-icon.component.html
- Format files on `master` branch with Prettier
I ran the `npm run format` script, and this is the result.
I'm also creating a PR to automatically check if incoming changes follow the Prettier rules, see:
- #409
> chore: format files with Prettier

- src/app/cheat-sheets/game-base/space-age/space-age.component.html
- Rewrite parts of the Space Age component
- Write short sentences
- Use common words and phrases
- Reduce capitalization
Rewriting a small section so the review is easier. 😉
> Rewrite space age component

- src/app/cheat-sheets/game-base/science/science.component.html
- Rewrite science component
- Reduce capitalization
- Write short sentences
Some small text changes. I'm _not_ changing the layout, or styling.
> Rewrite science component

- src/app/cheat-sheets/game-base/modules-and-beacons/modules-and-beacons.component.html
- src/app/cheat-sheets/game-base/space-age/space-age.component.html
- Add table with pros and cons of each module.
- Move tips for each module into their own `h4`, with list layout
- Move tip about using quality machines to Space Age section, and highlight the Asteroid collector. (It gets extra arms, and moves faster!)
Screenshots:
> Rewrite modules and beacons

- src/app/cheat-sheets/game-base/vehicle-fuel-bonus/vehicle-fuel-bonus.component.html
- Add platform sentence before list of tips.
- Rewrite list items.
- Rewrite table captions.
- Reduce capitalization in table headers.
> Rewrite vehicle fuel bonus section

- CONTRIBUTING.md
- Rewrite contributing guide
- Use one sentence per line pattern (makes it easy to move sentences around later)
- Use human-readable names for links (like the link to Stackoverflow)
- Capitalize proper nouns like Git, Stackoverflow, GitKraken, and so on
- Add descriptive headings
- Break up long lists by adding headings
I assume you'll merge the Pull Request template I'm making here:
- #454 
If you're _not merging_ #454, I'll need to edit my PR _before_ you merge it. 😉
> Rewrite CONTRIBUTING.md
