deniszholob/factorio-cheat-sheet

- src/app/views/cheat-sheets/science/science.component.html
Looks like something got added to Factorio Planner that introduced an off-by-one error into the recipe. The link was for maxing out five assembling machines worth of flying robot frames and no yellow science.
> Update Factorio Planner link

- src/app/views/cheat-sheets/nuclear-power/nuclear-power.component.html
- src/app/views/cheat-sheets/nuclear-power/nuclear-power.component.ts
This fixes #72 by adding nuclear reactor efficiency to the nuclear ratio table. Screenshot:
> Fix #72 added nuclear reactor efficiency

- src/app/views/cheat-sheets/belt-throughput/belt-throughput.component.html
- src/assets/data/belt-throughput.json
Throughput is 15 for yellow, 30 for red, 45 for blue.
https://wiki.factorio.com/Tutorial:Cheat_sheet#Belt_throughput
> Belt troughput speeds for 0.17 (#96)

- src/assets/data/mining.json
The mining rate of stone was changed in 0.17 to be the same as iron, copper, and coal. This change removes the stone only row.
> Combine Stone with the other ores that have the same mining rate.

- src/app/views/cheat-sheets/basic-power/basic-power.component.html
- src/app/views/cheat-sheets/belt-throughput/belt-throughput.component.html
- src/app/views/cheat-sheets/belt-throughput/belt-throughput.component.ts
- src/app/views/cheat-sheets/cargo-wagon-transfer/cargo-wagon-transfer.component.html
- src/app/views/cheat-sheets/oil-refining/oil-refining.component.html
- src/app/views/cheat-sheets/tips/tips.component.html
- src/assets/data/basic-power.json
- src/assets/data/belt-throughput.json
* Boilers supported by fuel belt: 3.6MW -> 1.8MJ
* Add more tips with new 0.17 features (CTRL+C, etc..)
* Refactor html line lengs to be smaller
* Change Blet Throughput table and include underground distance
* Move number data from html to json for basic power (+1 squashed commits)
* Minor oil formatting
> #149 More Fixes for 0.17

- src/app/views/cheat-sheets/nuclear-power/nuclear-power.component.html
- src/app/views/cheat-sheets/tips/tips.component.html
Add section on rich text shortcut: To quickly get a rich text tag for an item: open the console, then shift-click on the item (eg in your inventory, a chest, etc.) A rich text tag for that item appears in the console and can be copied.
and
Nuke Turbines formula 5.8MW => 5.82MW
> Two small fixes for issue 180

- src/index.html
Currently the Jura font at weight `700` is rendered incorrectly on some browsers, as per issue #229. This is due to the web font at this weight not being requested from Google Fonts. This PR  specifies the web font weights we need from Google fonts, and fixes the issue.
**Screenshot before:** 
**Screenshot after**
(Screenshots are a little blurry due to being taken on browserstack in mac, but I've also tested the fix on Windows machine and looks even better 👍 )
> Closes #229 - problem with Jura font-weight 700

- src/app/views/cheat-sheets/tips/tips.component.html
Blueprints in map view are no longer limited to radar coverage.  (As of 1.1 you'll be able to create a blueprint, deconstruct, and cut/copy without coverage as well, but that's not mentioned here anyway.)
> Update tip: Blueprints in map view

- src/app/views/cheat-sheets/modules-and-beacons/modules-and-beacons.component.html
- src/app/views/cheat-sheets/modules-and-beacons/modules-and-beacons.component.ts
Closes #302 * "Consumption" here was misleading, it was referring to consuming the output, i.e. the Production Rate of the machine.
> #302 Change "Consumption" to "Production"

- src/app/views/cheat-sheets/links/links.data.ts
There is a banner at the top of `https://teoxoy.github.io/factorio-blueprint-editor/` saying that the owner is migrating the Blueprint Maker site to `https://fbe.teoxoy.com/`. This simply updates the URL to point directly to the new site.
> Update Blueprint Maker URL to new URL per banner

- src/app/views/cheat-sheets/links/links.data.ts
- src/app/views/cheat-sheets/material-processing/material-processing.component.html
- src/app/views/nav/nav.component.html
- src/styles/_side-nav.scss
- src/styles/_switch.scss
* Decrease nav padding slightly to remove scrollbars on 1080p screens and larger
* Comment out the nav close button to save vertical space as there is the arrow does the same thing
* Tweak switch styles to make it less long and address division without calc() deprecation notice
* Move blueprint + map links to own designs category
* closes #337 add titles for material processing cell and rename buildings to factories
> Style Tweaks

- src/app/views/nav/nav.component.html
- src/styles/_side-nav.scss
@deniszholob I had a go at doing something different with the side-nav.  Tested with my iPhone running against the build on my local machine and it seems to be ok. 
This stops the nav-bar from trying to reflow all the text when opening and closing because it never changes size, just slides off the screen.
I also adjusted the transition speed because half a second is a little long.
Let me know what you think.
#361
> use css transforms for the side-nav

- src/app/cheat-sheets/game-base/basic-power/basic-power.component.html
- src/app/cheat-sheets/game-base/basic-power/basic-power.data.ts
It should say "A steam boiler consumes 1.8MJ of fuel per second" or 1.8MW.
> Basic power entry incorrectly states that a boiler consumes 1.8 MJ of fuel

- .vscode/extensions.json
"Disabling this extension as its functionality has been absorbed by VS Code main html extension."
> Remove Deprecated html-snippet

- src/app/cheat-sheets/game-base/balancers/balancers.component.html
- src/app/cheat-sheets/game-base/belts/belts.component.html
- src/app/cheat-sheets/game-base/cargo-wagon-transfer/cargo-wagon-transfer.component.html
- src/app/cheat-sheets/game-base/combat/combat.component.html
- src/app/cheat-sheets/game-base/fluid-wagon-transfer/fluid-wagon-transfer.component.html
- src/app/cheat-sheets/game-base/mining/mining.component.html
- src/app/cheat-sheets/game-base/modules-and-beacons/modules-and-beacons.component.html
- src/app/cheat-sheets/game-base/nuclear-power/nuclear-power.component.html
- src/app/cheat-sheets/game-base/oil-refining/oil-refining.component.html
- src/app/shared/factorio-icon/factorio-icon.component.html
Closes #110
Closes #173 
When I ran my builds and tested the images lazyloaded just fine, however the videos are not playing for me with oil refining.  Can you please double check that?
> Manually added lazy load

- angular.json
- Disable Angular asking for analytics
When you run `npm run start` it runs the `ng serve --port 9009` command. On a fresh installation, Angular then asks for permission to gather some analytics. 
I automated setting up a developer environment. You'll get a PR from me soon:
- #407
For the automated setup to work properly, Angular should _not_ ask for input during the Codespace build steps.
I told Angular to stop asking for permission, by setting `analytics=false` in the `angular.json` config file.
See the [Angular CLI configuration options](https://angular.dev/reference/configs/workspace-config#angular-cli-configuration-options) table, search for the `analytics` keyword.
> chore: disable Angular analytics

- package.json
- Cache the result from earlier Prettier runs, to speed up running Prettier at a later time
You can cache the result of Prettier runs locally. That way:
- The first run is a bit slower (due to needing to write a cache file)
- But later Prettier runs will only check files that change, so it's really fast
Read the [Prettier docs for the CLI, `--cache` config option](https://prettier.io/docs/en/cli.html#--cache) to learn the full details.
> chore: cache Prettier runs

- .devcontainer/devcontainer.json
- Create `.devcontainer` file with GitHub Codespaces setup
- Use Node 22 as basis for the container image
With my changes you can:
- Create a development enviroment by clicking on the green `<> Code` button on any branch of your repository (this also works on forks that have pulled in this change)
- You can use the browser to work on your change, and see the preview of the live site
- You do not need to worry about installing the right dependencies
You will need to update the `"image": "mcr.microsoft.com/devcontainers/javascript-node:1-22-bookworm",` part from time to time. GitHub added a Dependabot config during the setup steps for the Node.js container.
I recommend using a bot to update the container file regularly. It's easy to forget. 😄 
- [GitHub Docs, GitHub Codespaces …
> chore: create devcontainer for GitHub Codespaces

- .github/workflows/lint.yml
- Create lint workflow that runs the `format:check` script on:
- pushes to `master`
- incoming PRs
This repository has files that are not following the Prettier formatting. I'll create a another PR to fix the formatting of the files on `master`.
But to prevent future PRs/pushes with bad formatting, I'd like us to check automatically if the changes follow the linter rules.
> chore: create lint workflow

- src/app/cheat-sheets/game-base/material-processing/material-processing.component.html
- src/app/cheat-sheets/game-base/material-processing/material-processing.component.ts
- src/app/cheat-sheets/game-base/material-processing/material-processing.data.ts
- src/app/models/MaterialProcessingData.model.ts
I added turbo belts to the material processing area. I've not necessarily used them for this (since you get foundries etc.), but I found that I'd like to see the ratio.
If someone could also please double-check the amounts :)
I also resolved a small deprecation.
> add turbo belts to material processing

- src/app/cheat-sheets/game-base/cargo-wagon-transfer/cargo-wagon-transfer.component.html
- Partial rewrite of the Cargo wagon transfer section
- Link to the Factorio Wiki page for Inserter capacity bonuses
- Grammar and style fixes
Rewriting to use simple words and phrases, and shorter sentences.
> Rewrite cargo wagon transfer section

- .github/workflows/branch.yml
- .github/workflows/main.yml
- Update `actions/upload-artifact@v3` to `v4`
- Update `actions/download-artifact@v3` to `v4` 
My PR to update the text in the overview component is automatically failing, because we're using old versions of these actions.
I only bumped the number from v3 to v4. I don't yet know if this is enough to get things working again. Testing GitHub Actions locally is nearly impossible...
- https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
- https://github.blog/news-insights/product-news/get-started-with-v4-of-github-actions-artifacts/#compatibility
> Bump upload and download artifacts actions to v4

- src/app/layout/overview/overview.component.html
- Use simpler words and phrases
- Convert long "thank you" sentence into a list
- Pull ratio info into own hacky section (should be it's own small section later, I think)
- Fix styling of the list (use commas and full stops at list item end)
- Remove whitespace in the link texts
- Drop special styling for the "New players should" and "Factorio-only content" text
- Some other small things
Rewriting the top of the page.
> Rewrite overview component text

- src/app/cheat-sheets/game-base/tips/tips.component.html
- Rewrite the shortcuts in the tips section
- Use simple words and phrases
- Write short sentences
- End list items with a full stop
- Use correct symbol for the tilde character: ~
- Add whitespace in the keyboard command shortcuts
- Separate some items into two list items
Improving the tips in the shortcut section. 😄
> Rewrite shortcuts in tips section

- src/app/cheat-sheets/game-base/tips/tips.component.html
- Add keyboard shortcuts for these views:
- M for the map
- O for the trains
- P for the production
I did _not_ add the tip about using Q to deselect items. I just hover over the next thing I want to select, and use Q then. 😉 
Closes #419
> Add keyboard shortcuts

- src/app/cheat-sheets/game-base/tips/tips.component.html
- Convert list of shortcuts to table layout
- Put list of copy/paste tips in new `h5` section
> Convert shortcut list to table

- src/app/cheat-sheets/game-base/links/links.data.ts
- Add link for [ElderAxe's Patreon page with Factorio blueprints](https://www.patreon.com/ElderAxe)
- Move `url` field for `Train Intersections` down, to match the layout of the previous entries
I like ElderAxe's blueprints. 😄 Their blueprints are released to the public for _free_ after about 90 days usually.
> Add link to ElderAxe's blueprints
